---
# tasks file for roles/ec2_instance_create

- ec2:
    key_name: "{{ ec2_instance_create_key }}"
    instance_type: t2.micro
    image: "{{ ec2_instance_create_image }}"
    wait: yes
    group: "{{ ec2_instance_create_secg }}"
    count: "{{ ec2_instance_create_count }}"
    vpc_subnet_id: "{{ ec2_instance_create_vpc_id }}"
    assign_public_ip: yes
    region: "{{ ec2_instance_create_region }}"
    instance_tags:
      Name: ansible-target
      automation_group: "{{ ec2_instance_create_automation_group_name }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: standard
        volume_size: 10
        delete_on_termination: true
  register: ec2

- debug: var=ec2

- add_host:
    host: "{{ item.public_ip }}"
    group: "{{ ec2_instance_create_inv_group_name }}"
    ansible_ssh_user: centos
    ansible_ssh_private_key_file: aitac-automation-key.pem
  with_items: "{{ ec2.instances }}"

- debug: var=hostvars