- hosts: target
  gather_facts: True
  become: yes

  tasks:
    - import_role:
        names: set_fast_repo

    - yum:
        name: httpd
        state: latest

    - systemd:
        name: httpd
        state: started
        enabled: yes

    - template:
        src: index.html.j2
        dest: /var/www/html/index.html
