- hosts: localhost
  gather_facts: False

  tasks:
    - add_host:
        host: "{{ item.public_ip }}"
        group: tag_automation_group_target
        ansible_ssh_user: centos
        ansible_ssh_private_key_file: aitac-automation-key.pem
      with_items: "{{ ec2.instances }}"


- hosts: tag_automation_group_target
  gather_facts: False

  tasks:

    - name: TEST SSH port is up?
      wait_for:
        host: "{{ (ansible_ssh_host | default(ansible_host)) | default(inventory_hostname) }}"
        port: 22
        delay: 180
        state: started
        timeout: 600
      connection: local

    - ping:
